# Generated by Django 3.0.6 on 2020-07-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_auto_20200720_1429'),
        ('teacher', '0007_auto_20200720_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Group.Group'),
        ),
    ]
