# Generated by Django 3.0.6 on 2020-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('group_email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
