# Generated by Django 3.0.6 on 2020-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_auto_20200719_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=128),
        ),
    ]
