# Generated by Django 3.0.6 on 2020-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_auto_20200720_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
