# Generated by Django 3.0.6 on 2020-07-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_auto_20200720_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
    ]
