# Generated by Django 3.0.6 on 2020-07-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200719_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
